version: "3.4"

services:
  proxy:
    image: haproxy:alpine
    volumes:
      - "./docker/proxy:/usr/local/etc/haproxy:ro"

    ports:
      - "80:80"
      - "443:443"

  app:
    image: anthonyporthouse/rss_app:latest

    build:
      context: .
      dockerfile: docker/app/Dockerfile

    volumes:
      - "./src/app/public:/go/src/app/public"
      - "./src/app/resources:/go/src/app/resources"

    restart: always

    depends_on:
      - api

  api:
    image: anthonyporthouse/rss_api:latest

    build:
      context: .
      dockerfile: docker/api/Dockerfile

    ports:
      - "1234:1234"

    restart: always

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: rss
      DB_NAME: rss
      DB_PASS: password

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rss
      MYSQL_USER: rss
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"